#!/usr/bin/env bash
# Builds static/blimp/home-art.js: temper/src/art compiled by Temper's JS
# backend and bundled with temper-core, plus the few lines that draw the
# homepage's background with it.
#
# The server draws the background once (desk_art, the same module through
# the Blimp backend) so the page has one with scripts off. The browser
# draws a new one on every page view: a picture costs the Blimp
# interpreter 50ms or more, which a one-thread server cannot spend per
# request, and costs this bundle about 0.02ms. Same seed, same bytes on
# both backends; this script checks that before it writes the file.
#
# Needs the temper CLI (build.sh's $TEMPER), node and npx (esbuild).
# Run it when temper/src/art changes, and commit the output.
set -euo pipefail
cd "$(dirname "$0")/../.."
TEMPER="${TEMPER:-/Users/bg/code/temper-blimp-112/temper/cli/build/install/temper/bin/temper}"
TEMPER_JAVA_HOME="${TEMPER_JAVA_HOME:-/opt/homebrew/opt/openjdk@21}"
BLIMP="${BLIMP:-blimp}"
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

mkdir -p "$work/src/art"
cp temper/src/art/art.temper.md "$work/src/art/"
printf '# Art, for the browser\n\n    export let name = "art-js";\n' > "$work/src/config.temper.md"
(cd "$work" && JAVA_HOME="$TEMPER_JAVA_HOME" "$TEMPER" build -b js -w src > build.log 2>&1) || { cat "$work/build.log" >&2; exit 1; }
js="$work/src/temper.out/js"

cat > "$js/entry.mjs" <<'EOF'
import { art_shapes } from './art-js/art.js'
// The homepage's background: a new Bauhaus picture per page view, into the
// <svg> the server drew one into (src/60_desktop.blimp's desk_art).
const svg = document.querySelector('.bg-art svg')
if (svg) {
  const r = new Uint32Array(1)
  crypto.getRandomValues(r)
  const seed = (r[0] % 16777215) + 1
  svg.innerHTML = art_shapes(seed, 'bauhaus', 1600, 1000)
  svg.setAttribute('data-seed', String(seed))
}
EOF
cat > "$js/parity.mjs" <<'EOF'
import { art_shapes } from './art-js/art.js'
import { createHash } from 'node:crypto'
const seeds = [12345, 20727, 16000000]
console.log(createHash('sha256').update(seeds.map(s => art_shapes(s, 'bauhaus', 1600, 1000)).join('')).digest('hex'))
EOF
(cd "$js" && npx -y esbuild@0.24.0 parity.mjs --bundle --platform=node --format=esm --alias:@temperlang/core=./temper-core/index.js --outfile=parity.bundle.mjs --log-level=warning)
js_sum=$(node "$js/parity.bundle.mjs")

# The same three pictures through the Blimp backend, as the server draws them.
./build.sh > /dev/null
{ cat _build/temper.blimp; printf 'puts(sha256(concat(art_shapes(12345, "bauhaus", 1600, 1000), art_shapes(20727, "bauhaus", 1600, 1000), art_shapes(16000000, "bauhaus", 1600, 1000))))\n'; } > "$work/parity.blimp"
blimp_sum=$("$BLIMP" "$work/parity.blimp" | tail -1)
if [ "$js_sum" != "$blimp_sum" ]; then
  echo "the JS and Blimp backends draw different pictures: $js_sum vs $blimp_sum" >&2
  exit 1
fi

(cd "$js" && npx -y esbuild@0.24.0 entry.mjs --bundle --format=iife --minify --alias:@temperlang/core=./temper-core/index.js --outfile=bundle.js --log-level=warning)
{
  printf '// Generated by static/blimp/home-art.sh from temper/src/art; do not edit.\n'
  cat "$js/bundle.js"
} > static/blimp/home-art.js
echo "static/blimp/home-art.js: $(wc -c < static/blimp/home-art.js | tr -d ' ') bytes, backends agree ($js_sum)"
